=== otmanabdoun/IHM-Python/2- Data Management - XML DTD XSL/Factures/tpxml/tp1.dtd
<!ELEMENT Gestion_Commande (client+,produit+)>
<!ELEMENT client (Commande)>
<!ATTLIST client
          nom CDATA #REQUIRED>
<!ELEMENT Commande (ligne_Commande)>
<!ELEMENT ligne_Commande (#PCDATA)>
<!ATTLIST ligne_Commande
          id_prod CDATA #REQUIRED
          qte_cmd CDATA #REQUIRED>
<!ELEMENT produit (#PCDATA)>
<!ATTLIST produit
          id_prod ID #REQUIRED
>

=== otmanabdoun/IHM-Python/2- Data Management - XML DTD XSL/Factures/tpxml/tp1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Gestion_commande SYSTEM "tp1.dtd">
<?xml-stylesheet type="text/xsl" href="tp1.xsl"?>
<Gestion_Commande>



                    <client nom="FARDALI">

                    <Commande>
                    <ligne_Commande qte_cmd="66" id_prod="produit numero 1">
                    </ligne_Commande>

                    </Commande>

                    </client>
                    <client nom="SAAIDI">

                    <Commande>
                    <ligne_Commande qte_cmd="66" id_prod="produit numero 2">
                    </ligne_Commande>

                    </Commande>

                    </client>
                    <client nom="BENGAAD">

                    <Commande>
                    <ligne_Commande qte_cmd="66" id_prod="produit numero 3">
                    </ligne_Commande>

                    </Commande>

                    </client>
                    <client nom="GHANNOUCHI">

                    <Commande>
                    <ligne_Commande qte_cmd="66" id_prod="produit numero 4">
                    </ligne_Commande>

                    </Commande>

                    </client>

          
                    <produit id_prod="produit numero 1">


                    </produit>
                    <produit id_prod="produit numero 2">


                    </produit>
                    <produit id_prod="produit numero 3">


                                        </produit>
                    <produit id_prod="produit numero 4">


                                        </produit>







</Gestion_Commande>
